import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.js';
import {readTouch,snapTurn} from '../vr-input.js';
import {createVR} from '../vr-mode.js';
const buttons=Array.from({length:6},()=>({pressed:false}));
const source={handedness:'right',gamepad:{mapping:'xr-standard',axes:[0,0,.9,-1],buttons}};
buttons[4].pressed=true;assert(readTouch(source).jump);assert.equal(readTouch(source).y,-1);
source.gamepad.axes[2]=.1;assert.equal(readTouch(source).x,0);
assert.equal(readTouch({gamepad:{mapping:'',axes:[]}}).x,0);
assert.equal(snapTurn(1,true).angle,-Math.PI/6);assert.equal(snapTurn(1,false).angle,0);assert(snapTurn(0,false).ready);
const ctx=new Proxy({measureText:t=>({width:t.length*12})},{get:(o,k)=>k in o?o[k]:()=>{}});
globalThis.document={createElement:()=>({getContext:()=>ctx})};
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(65,1,.1,800);scene.add(camera);
const controllers=[new THREE.Group(),new THREE.Group()],grips=[new THREE.Group(),new THREE.Group()];
let currentSession=null,vrState=false,attacks=0,jumps=0,lastPaused=false,exits=0;
const player={x:0,y:3,z:0,health:100};
const game={getPlayer:()=>player,setVR:v=>vrState=v,update:(dt,keys,paused,input)=>{lastPaused=paused;if(!paused)player.z-=input.forward*dt;},attack:()=>attacks++,jump:()=>jumps++};
const session=new EventTarget();session.visibilityState='visible';session.end=async()=>{session.dispatchEvent(new Event('end'));};
const renderer={xr:{getController:i=>controllers[i],getControllerGrip:i=>grips[i],setReferenceSpaceType:t=>assert.equal(t,'local-floor'),setFramebufferScaleFactor(){},setSession:async s=>{currentSession=s;},getCamera:()=>camera,updateCamera:()=>{camera.position.set(0,1.6,0);camera.updateMatrixWorld(true);}}};
const vr=await createVR({renderer,scene,camera,game,session,onPortalRay:()=>false,onExit:()=>exits++,onDesktopPortal(){}});
assert(vr.active&&vrState);assert.equal(currentSession,session);
source.gamepad.axes=[0,0,0,0];controllers[1].dispatchEvent({type:'connected',data:source});
vr.update(1/60);assert.equal(jumps,1);vr.update(1/60);assert.equal(jumps,1,'holding A must not consume both jumps');
buttons[4].pressed=false;vr.update(1/60);buttons[4].pressed=true;vr.update(1/60);assert.equal(jumps,2);
controllers[1].dispatchEvent({type:'selectstart'});assert.equal(attacks,1,'right trigger swings');
vr.showPortal({name:'About',description:'A portal preview.',url:'https://example.com'});vr.update(1/60);assert(lastPaused&&vr.paused,'headset portal pauses game');
await vr.end();assert(!vr.active&&!vrState);assert.equal(exits,1);assert.equal(camera.parent,scene);assert.equal(camera.position.y,4.55);assert.equal(camera.fov,65);
console.log('Touch mapping, snap turn, jump edges, trigger attack, headset portal pause, and VR cleanup passed (mock XR session).');
